name: MastersApp
description: Habit Tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  get: ^4.6.5
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.2
  path_provider: ^2.0.14
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_screenutil: ^5.7.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700